from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(889, 614)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/To-do.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.menu_bar = QtWidgets.QWidget(self.centralwidget)
        self.menu_bar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.menu_bar.setObjectName("menu_bar")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.menu_bar)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.menu_bar)
        self.verticalScrollBar.setMaximumSize(QtCore.QSize(10, 16777215))
        self.verticalScrollBar.setStyleSheet("")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout_3.addWidget(self.verticalScrollBar, 4, 2, 11, 1, QtCore.Qt.AlignRight)
        self.line_3 = QtWidgets.QFrame(self.menu_bar)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 8, 0, 1, 2)
        self.complete_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.complete_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/complete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.complete_button.setIcon(icon1)
        self.complete_button.setCheckable(True)
        self.complete_button.setAutoExclusive(True)
        self.complete_button.setFlat(True)
        self.complete_button.setObjectName("complete_button")
        self.gridLayout_3.addWidget(self.complete_button, 7, 0, 1, 2)
        self.all_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.all_button.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.all_button.setIcon(icon2)
        self.all_button.setCheckable(True)
        self.all_button.setAutoExclusive(True)
        self.all_button.setFlat(True)
        self.all_button.setObjectName("all_button")
        self.gridLayout_3.addWidget(self.all_button, 6, 0, 1, 2)
        self.work_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.work_button.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/work.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.work_button.setIcon(icon3)
        self.work_button.setCheckable(True)
        self.work_button.setAutoExclusive(True)
        self.work_button.setFlat(True)
        self.work_button.setObjectName("work_button")
        self.gridLayout_3.addWidget(self.work_button, 9, 0, 1, 2)
        self.important_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.important_button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.important_button.setIcon(icon4)
        self.important_button.setCheckable(True)
        self.important_button.setAutoExclusive(True)
        self.important_button.setFlat(True)
        self.important_button.setObjectName("important_button")
        self.gridLayout_3.addWidget(self.important_button, 5, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_box = QtWidgets.QLineEdit(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_box.setFont(font)
        self.search_box.setText("")
        self.search_box.setObjectName("search_box")
        self.horizontalLayout_3.addWidget(self.search_box)
        self.search_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("")
        self.search_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon5)
        self.search_button.setFlat(True)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_3.addWidget(self.search_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.menu_bar)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.menu_bar)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 14, 1, 1, 1)
        self.today_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.today_button.setFont(font)
        self.today_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.today_button.setIcon(icon6)
        self.today_button.setShortcut("")
        self.today_button.setCheckable(True)
        self.today_button.setAutoExclusive(True)
        self.today_button.setFlat(True)
        self.today_button.setObjectName("today_button")
        self.gridLayout_3.addWidget(self.today_button, 4, 0, 1, 2)
        self.new_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_button.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_button.setIcon(icon7)
        self.new_button.setCheckable(True)
        self.new_button.setAutoExclusive(True)
        self.new_button.setFlat(True)
        self.new_button.setObjectName("new_button")
        self.gridLayout_3.addWidget(self.new_button, 13, 0, 1, 2)
        self.shopping_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.shopping_button.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/shopping.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shopping_button.setIcon(icon8)
        self.shopping_button.setCheckable(True)
        self.shopping_button.setAutoExclusive(True)
        self.shopping_button.setFlat(True)
        self.shopping_button.setObjectName("shopping_button")
        self.gridLayout_3.addWidget(self.shopping_button, 12, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_icon = QtWidgets.QLabel(self.menu_bar)
        self.title_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.title_icon.setObjectName("title_icon")
        self.horizontalLayout_2.addWidget(self.title_icon)
        self.app_title = QtWidgets.QLabel(self.menu_bar)
        self.app_title.setMaximumSize(QtCore.QSize(250, 16777215))
        self.app_title.setObjectName("app_title")
        self.horizontalLayout_2.addWidget(self.app_title)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.menu_bar)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 15, 0, 1, 3)
        self.add_list_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.add_list_button.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_list_button.setIcon(icon9)
        self.add_list_button.setCheckable(True)
        self.add_list_button.setAutoExclusive(True)
        self.add_list_button.setFlat(True)
        self.add_list_button.setObjectName("add_list_button")
        self.gridLayout_3.addWidget(self.add_list_button, 16, 0, 1, 3)
        self.exercise_button = QtWidgets.QPushButton(self.menu_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exercise_button.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/gym.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exercise_button.setIcon(icon10)
        self.exercise_button.setCheckable(True)
        self.exercise_button.setAutoExclusive(True)
        self.exercise_button.setFlat(True)
        self.exercise_button.setObjectName("exercise_button")
        self.gridLayout_3.addWidget(self.exercise_button, 11, 0, 1, 2)
        self.gridLayout_4.addWidget(self.menu_bar, 0, 0, 1, 1)
        self.MainWindow = QtWidgets.QStackedWidget(self.centralwidget)
        self.MainWindow.setAutoFillBackground(False)
        self.MainWindow.setStyleSheet("")
        self.MainWindow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainWindow.setObjectName("MainWindow")
        self.Today = QtWidgets.QWidget()
        self.Today.setObjectName("Today")
        self.gridLayout = QtWidgets.QGridLayout(self.Today)
        self.gridLayout.setObjectName("gridLayout")
        self.today_list_title = QtWidgets.QLabel(self.Today)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        self.today_list_title.setFont(font)
        self.today_list_title.setObjectName("today_list_title")
        self.gridLayout.addWidget(self.today_list_title, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(173, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.new_task_edit = QtWidgets.QLineEdit(self.Today)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_task_edit.setFont(font)
        self.new_task_edit.setText("")
        self.new_task_edit.setObjectName("new_task_edit")
        self.gridLayout.addWidget(self.new_task_edit, 3, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.Today)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 3)
        self.clear_list_button = QtWidgets.QPushButton(self.Today)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_list_button.setFont(font)
        self.clear_list_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_list_button.setIcon(icon11)
        self.clear_list_button.setCheckable(False)
        self.clear_list_button.setAutoExclusive(True)
        self.clear_list_button.setFlat(True)
        self.clear_list_button.setObjectName("clear_list_button")
        self.gridLayout.addWidget(self.clear_list_button, 0, 2, 1, 1)
        self.add_task_button = QtWidgets.QPushButton(self.Today)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_task_button.setFont(font)
        self.add_task_button.setIcon(icon9)
        self.add_task_button.setCheckable(True)
        self.add_task_button.setAutoExclusive(True)
        self.add_task_button.setFlat(True)
        self.add_task_button.setObjectName("add_task_button")
        self.gridLayout.addWidget(self.add_task_button, 3, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.Today)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 2, 0, 1, 3)
        self.MainWindow.addWidget(self.Today)
        self.Important = QtWidgets.QWidget()
        self.Important.setObjectName("Important")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Important)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.important_list_title = QtWidgets.QLabel(self.Important)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        self.important_list_title.setFont(font)
        self.important_list_title.setObjectName("important_list_title")
        self.gridLayout_5.addWidget(self.important_list_title, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.add_task_button_2 = QtWidgets.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_task_button_2.setFont(font)
        self.add_task_button_2.setText("")
        self.add_task_button_2.setIcon(icon9)
        self.add_task_button_2.setCheckable(False)
        self.add_task_button_2.setFlat(True)
        self.add_task_button_2.setObjectName("add_task_button_2")
        self.gridLayout_5.addWidget(self.add_task_button_2, 3, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.Important)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 2, 0, 1, 3)
        self.new_task_edit_2 = QtWidgets.QLineEdit(self.Important)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_task_edit_2.setFont(font)
        self.new_task_edit_2.setText("")
        self.new_task_edit_2.setObjectName("new_task_edit_2")
        self.gridLayout_5.addWidget(self.new_task_edit_2, 3, 0, 1, 2)
        self.clear_list_button_2 = QtWidgets.QPushButton(self.Important)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_list_button_2.setFont(font)
        self.clear_list_button_2.setText("")
        self.clear_list_button_2.setIcon(icon11)
        self.clear_list_button_2.setCheckable(False)
        self.clear_list_button_2.setFlat(True)
        self.clear_list_button_2.setObjectName("clear_list_button_2")
        self.gridLayout_5.addWidget(self.clear_list_button_2, 0, 2, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.Important)
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_2.setSelectionRectVisible(False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_5.addWidget(self.listWidget_2, 1, 0, 1, 3)
        self.MainWindow.addWidget(self.Important)
        self.All = QtWidgets.QWidget()
        self.All.setObjectName("All")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.All)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.all_list_title = QtWidgets.QLabel(self.All)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        self.all_list_title.setFont(font)
        self.all_list_title.setObjectName("all_list_title")
        self.gridLayout_6.addWidget(self.all_list_title, 0, 0, 1, 1)
        self.new_task_edit_3 = QtWidgets.QLineEdit(self.All)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_task_edit_3.setFont(font)
        self.new_task_edit_3.setText("")
        self.new_task_edit_3.setObjectName("new_task_edit_3")
        self.gridLayout_6.addWidget(self.new_task_edit_3, 3, 0, 1, 2)
        self.clear_list_button_3 = QtWidgets.QPushButton(self.All)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_list_button_3.setFont(font)
        self.clear_list_button_3.setText("")
        self.clear_list_button_3.setIcon(icon11)
        self.clear_list_button_3.setFlat(True)
        self.clear_list_button_3.setObjectName("clear_list_button_3")
        self.gridLayout_6.addWidget(self.clear_list_button_3, 0, 2, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.All)
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_3.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_6.addWidget(self.listWidget_3, 1, 0, 1, 3)
        self.add_task_button_3 = QtWidgets.QPushButton(self.All)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_task_button_3.setFont(font)
        self.add_task_button_3.setText("")
        self.add_task_button_3.setIcon(icon9)
        self.add_task_button_3.setFlat(True)
        self.add_task_button_3.setObjectName("add_task_button_3")
        self.gridLayout_6.addWidget(self.add_task_button_3, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(223, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.All)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 2, 0, 1, 3)
        self.MainWindow.addWidget(self.All)
        self.Completed = QtWidgets.QWidget()
        self.Completed.setObjectName("Completed")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Completed)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.completed_list_title = QtWidgets.QLabel(self.Completed)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        self.completed_list_title.setFont(font)
        self.completed_list_title.setObjectName("completed_list_title")
        self.gridLayout_7.addWidget(self.completed_list_title, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(169, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 1, 1)
        self.clear_list_button_4 = QtWidgets.QPushButton(self.Completed)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_list_button_4.setFont(font)
        self.clear_list_button_4.setText("")
        self.clear_list_button_4.setIcon(icon11)
        self.clear_list_button_4.setFlat(True)
        self.clear_list_button_4.setObjectName("clear_list_button_4")
        self.gridLayout_7.addWidget(self.clear_list_button_4, 0, 2, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.Completed)
        self.listWidget_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_7.addWidget(self.listWidget_4, 1, 0, 1, 3)
        self.MainWindow.addWidget(self.Completed)
        self.gridLayout_4.addWidget(self.MainWindow, 0, 1, 1, 1)
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        self.MainWindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "TaskMaster To-Do"))
        self.complete_button.setText(_translate("Window", "  Mastered"))
        self.all_button.setText(_translate("Window", "          All"))
        self.work_button.setText(_translate("Window", "       Work"))
        self.important_button.setText(_translate("Window", " Important"))
        self.search_box.setPlaceholderText(_translate("Window", "Search..."))
        self.today_button.setWhatsThis(_translate("Window", "<html><head/><body><p><br/></p></body></html>"))
        self.today_button.setText(_translate("Window", "     Today"))
        self.new_button.setText(_translate("Window", "          New"))
        self.shopping_button.setText(_translate("Window", "   Shopping"))
        self.title_icon.setText(_translate("Window", "<html><head/><body><p><img src=\":/Icons/To-do_1.png\"/></p></body></html>"))
        self.app_title.setText(_translate("Window", "<html><head/><body><p><span style=\" font-size:14pt;\">TaskMaster To-Do</span></p></body></html>"))
        self.add_list_button.setText(_translate("Window", "   New list"))
        self.exercise_button.setText(_translate("Window", "   Exercise"))
        self.today_list_title.setText(_translate("Window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Today</span></p></body></html>"))
        self.new_task_edit.setPlaceholderText(_translate("Window", "New task"))
        self.listWidget.setSortingEnabled(True)
        self.add_task_button.setText(_translate("Window", " "))
        self.important_list_title.setText(_translate("Window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Important</span></p></body></html>"))
        self.new_task_edit_2.setPlaceholderText(_translate("Window", "New task"))
        self.listWidget_2.setSortingEnabled(True)
        self.all_list_title.setText(_translate("Window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">All</span></p></body></html>"))
        self.new_task_edit_3.setPlaceholderText(_translate("Window", "New task"))
        self.listWidget_3.setSortingEnabled(True)
        self.completed_list_title.setText(_translate("Window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Mastered</span></p></body></html>"))

import Assets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
